"""
EA account swapper — a minimal, headless version of TcNo Account Switcher's
EA Desktop platform swap.

Each account's login session = the whole %LocalAppData%\Electronic Arts\EA Desktop
folder (OTT, cookie.ini, CEF cookies, telemetry.ini, ...). Because every account
was signed onto THIS machine, its pc_sign device trust stays valid, so restoring
a snapshot just changes who's logged in — then ea_minter scrapes that account's
token from EADesktop memory as usual.

    snapshot_current(dir)  -> save the live session into `dir`
    swap_to(dir, timeout)  -> kill EA, restore `dir`, relaunch, wait for token
    ensure_active(account) -> swap only if `account` isn't already active
"""

import logging
import os
import subprocess
import time
from pathlib import Path

from core import ea_minter

logger = logging.getLogger("eatokeer")

EA_DIR = Path(os.environ.get("LOCALAPPDATA", "")) / "Electronic Arts" / "EA Desktop"
EA_EXES = ["EADesktop.exe", "EABackgroundService.exe"]
ACTIVE_MARKER = Path(__file__).parent.parent / "active_account.txt"

# Subdirs/files not worth copying (regenerated by EA, or huge caches).
ROBO_EXCLUDE_DIRS = ["Logs", "IGOCache", "GPUCache", "ShaderCache", "DawnCache", "GrShaderCache"]
ROBO_EXCLUDE_FILES = ["*.log"]

# module-level: path to EADesktop.exe (set from config by main.py)
_ea_desktop_exe = r"C:\Program Files\Electronic Arts\EA Desktop\EA Desktop\EADesktop.exe"


def configure(ea_desktop_exe: str) -> None:
    global _ea_desktop_exe
    if ea_desktop_exe:
        _ea_desktop_exe = ea_desktop_exe


class SwapError(Exception):
    pass


# --------------------------------------------------------------------------- #
# Active-account bookkeeping
# --------------------------------------------------------------------------- #

def get_active() -> str | None:
    try:
        return ACTIVE_MARKER.read_text(encoding="utf-8").strip() or None
    except Exception:
        return None


def set_active(name: str) -> None:
    try:
        ACTIVE_MARKER.write_text(name, encoding="utf-8")
    except Exception as e:
        logger.warning(f"Could not write active_account marker: {e}")


# --------------------------------------------------------------------------- #
# EA process control
# --------------------------------------------------------------------------- #

def kill_ea() -> None:
    for exe in EA_EXES:
        try:
            subprocess.run(["taskkill", "/F", "/IM", exe], capture_output=True, timeout=15)
        except Exception as e:
            logger.debug(f"taskkill {exe}: {e}")
    time.sleep(1.5)  # let handles release before touching the folder


def start_ea() -> None:
    exe = Path(_ea_desktop_exe)
    if not exe.exists():
        raise SwapError(f"EADesktop.exe not found at {exe} (set ea_desktop_exe in config.json)")
    try:
        subprocess.Popen([str(exe)], cwd=str(exe.parent),
                         creationflags=getattr(subprocess, "DETACHED_PROCESS", 0))
        logger.info("Launched EA Desktop.")
    except Exception as e:
        raise SwapError(f"Failed to launch EA Desktop: {e}")


def _robocopy(src: Path, dst: Path, mirror: bool = True) -> None:
    args = ["robocopy", str(src), str(dst)]
    if mirror:
        args.append("/MIR")
    else:
        args.append("/E")
    for d in ROBO_EXCLUDE_DIRS:
        args += ["/XD", d]
    args += ["/XF"] + ROBO_EXCLUDE_FILES
    args += ["/R:1", "/W:1", "/NFL", "/NDL", "/NJH", "/NJS", "/NP"]
    result = subprocess.run(args, capture_output=True, text=True, timeout=600)
    # robocopy exit codes: 0-7 = success, >=8 = failure
    if result.returncode >= 8:
        raise SwapError(f"robocopy failed ({result.returncode}): {result.stdout[-300:]}")


# --------------------------------------------------------------------------- #
# Snapshot / swap
# --------------------------------------------------------------------------- #

def snapshot_current(snapshot_dir: str) -> None:
    """Save the currently logged-in EA session into snapshot_dir."""
    if not EA_DIR.exists():
        raise SwapError(f"EA Desktop folder not found: {EA_DIR}")
    dst = Path(snapshot_dir)
    if not dst.is_absolute():
        dst = Path(__file__).parent.parent / dst
    dst.mkdir(parents=True, exist_ok=True)
    logger.info(f"Snapshotting current EA session -> {dst}")
    kill_ea()
    _robocopy(EA_DIR, dst, mirror=True)
    logger.info("Snapshot complete.")


def wait_for_token(timeout: int = 60) -> bool:
    """Poll EADesktop memory until the bearer token is scrapeable, or timeout."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            tok = ea_minter.get_access_token_from_memory()
            if tok and len(tok) > 20:
                return True
        except Exception:
            pass
        time.sleep(2)
    return False


def swap_to(account: dict, timeout: int = 60) -> None:
    """Restore account's snapshot as the live EA session and wait until ready."""
    snap = account.get("snapshot", "")
    src = Path(snap)
    if not src.is_absolute():
        src = Path(__file__).parent.parent / src
    if not src.exists():
        raise SwapError(f"Snapshot folder missing for account '{account.get('name')}': {src}")

    logger.info(f"Swapping EA account -> {account.get('name')} ({src})")
    kill_ea()
    EA_DIR.mkdir(parents=True, exist_ok=True)
    _robocopy(src, EA_DIR, mirror=True)
    start_ea()

    if not wait_for_token(timeout):
        raise SwapError(
            f"Swapped to '{account.get('name')}' but no token appeared in "
            f"{timeout}s (EA App may still be starting / not logged in)."
        )
    set_active(account["name"])
    logger.info(f"Account '{account['name']}' is now active.")


def ensure_active(account: dict, timeout: int = 60) -> None:
    """Swap to `account` only if it isn't already the active one."""
    if get_active() == account["name"]:
        # Already the active account. The bearer token may simply not be
        # resident in EADesktop memory yet (EA App still starting up, or idle
        # between API calls). WAIT for it before resorting to a disruptive
        # kill + cold-restart, which only makes things slower/flakier.
        try:
            if ea_minter.get_access_token_from_memory():
                return
        except Exception:
            pass
        logger.info(
            f"'{account['name']}' is active but no token resident yet; "
            f"waiting up to {timeout}s for the EA App to surface it..."
        )
        if wait_for_token(timeout):
            logger.info(f"Token appeared for '{account['name']}' without a swap.")
            return
        logger.info(f"Still no token after {timeout}s; re-swapping '{account['name']}' as a last resort.")
    swap_to(account, timeout)
